### ISSUE TITLE
Events API change 

### ISSUE THREAD

**Issue by tobenary** [Ambro17/slackify#28]
The Events API is a system that apps can leverage to be notified of events and activity occurring in Slack. Changes are coming to the Events API that may impact your Slack apps.

On February 24th, 2021, event payloads from this system will send out authorization information related to the event in a new structure and format that returns a single authorization rather than a full list.

I got this email from Slack and I identified that your application still works with the old module. 
Am I right here? Or I miss understand that email correctly.

**Comment by Ambro17** [comment]
Hello! Thank you for the heads up.
I've read the changelog and I think it won't affect slackify since it assumes nothing from event payloads.

The change would be in the semantics of one key, but slackify only expects a JSON Payload and that assumption will still hold

I'll leave the issue open if you have any further doubts but I believe we won't have any problem.


https://api.slack.com/changelog/2020-09-15-events-api-truncate-authed-users

**Comment by tobenary** [comment]
I'm just asking because I got an email that I'm having a use of it. And
they named the same application that I am using your code with.

So... I'm just verify.


Note, I also sent them an email for triple check it.

**Comment by Ambro17** [comment]
Have you received a response?
